version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  web:
    restart: always
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - backend/.env

volumes:
  postgres_data:
    # external: true